-keep class com.nabil.usdtwallet.data.repository.** { *; }
-keep class org.bouncycastle.** { *; }
-dontwarn org.bouncycastle.**
-keep class io.github.novacrypto.** { *; }
-dontwarn io.github.novacrypto.**
-dontwarn okhttp3.**
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
